### PR TITLE
Fix lunging event

### PR DESCRIPTION
**Pull request by Misaka-ZeroTwo**
Obsolete IsAllowed cuz it will result desync. Also fixed it from not firing when it doesn't hit a target.

### CODE REVIEW

**Comment by Misaka-ZeroTwo** [comment]
tested, working fine.

**Comment by Misaka-ZeroTwo** [comment]
Fixes #1734

**Comment by Misaka-ZeroTwo** [comment]
waiting for another person to test it out

**Comment by louis1706** [comment]
> waiting for another person to test it out

then don't put tested but Required testing

**Comment by louis1706** [comment]
> IsAllowed false cause some desync

i put Base Game bug about the some desync i am suposing it's from NW

**Comment by Misaka-ZeroTwo** [comment]
IsAllowed removed.

**Review by louis1706 — APPROVED** [review]
Not tested by me but seems fine

**Review by louis1706 — CHANGES_REQUESTED** [review]
Fix breakchange

**Comment by joker-119** [comment]
Fix merge conflicts

**Pull request merged**
