### PR TITLE
EscapeScenario for Escaping Event

### PR DESCRIPTION
**Pull request by louis1706**

### CODE REVIEW

**Comment by louis1706** [comment]
Tested with DevTools on Windows Server

**Comment by joker-119** [comment]
Tbh I'm not sure why this is even necessary

**Comment by louis1706** [comment]
> Tbh I'm not sure why this is even necessary

the important change it's about than it's will be trigger with Ev.IsAllowed = false for 
other roletype than Scientist and Dclass

**Review by Thundermaker300 — APPROVED** [review]

**Comment by IRacle1** [comment]
> > Tbh I'm not sure why this is even necessary
> 
> the important change it's about than it's will be trigger with Ev.IsAllowed = false for 
> other roletype than Scientist and Dclass

Yeah, i happy that now NW make it possible, but it will be breaking change

**Comment by louis1706** [comment]
> > > Tbh I'm not sure why this is even necessary
> > 
> > 
> > the important change it's about than it's will be trigger with Ev.IsAllowed = false for
> > other roletype than Scientist and Dclass
> 
> Yeah, i happy that now NW make it possible, but it will be breaking change

it's not breaking ??

**Comment by Thundermaker300** [comment]
It's only breaking if somebody *relied* on the classd/scientist only escaping behavior, which is kind of a weird thing to rely on

**Comment by IRacle1** [comment]
> It's only breaking if somebody _relied_ on the classd/scientist only escaping behavior, which is kind of a weird thing to rely on

Maybe, but fact is fact -> event now calls for a few more situations

**Comment by louis1706** [comment]
> event now calls for a few more situations

still that not breaking change :3

**Comment by joker-119** [comment]
Technically anything that changes the behavior of the event qualifies as a breaking change, even if the plugins themselves can still use the event without recompile, because it requires code changes to use the event as it was intended in the plugin.

**Pull request merged**
