### PR TITLE
Player events

### PR DESCRIPTION
**Pull request by Ficus-x**

### CODE REVIEW

**Comment by louis1706** [comment]
VerifiedEventArgs and DestroyingEventArgs

**Comment by rus-skill-issue** [comment]
Bruh moment pull

**Comment by IRacle1** [comment]
I'm 90% sure that `IsAllowed = false` in these events will lead to things like server crash, I also want to know why they are needed at all

**Comment by IRacle1** [comment]
As Yamato said, `Verified` and `Destroying` events exist

**Pull request closed without merging**
