### PR TITLE
Make DisplayNickname return Nickname if it is null.

### PR DESCRIPTION
**Pull request by TheUltiOne**
I did not test it. It's such a simple addition.
If I _somehow_ made a stupid mistake, please troll :trollface: me.

### CODE REVIEW

**Comment by Michal78900** [comment]
Please sync your PR with the current `dev` branch.

**Comment by TheUltiOne** [comment]
mfw dumb

**Review by Michal78900 — APPROVED** [review]

**Review by Jesus-QC — APPROVED** [review]

**Comment by NaoUnderscore** [comment]
This PR is a breaking change and it doesn't make sense. Plugins that are using `string::IsNullOrEmpty` on `Player::DisplayNickname` will be broken. If it can be null, there's a reason. You can't spoof or change return types to avoid null. If I was a dev, I'd fight to reject this PR.

**Comment by PintTheDragon** [comment]
What's the point of this?

**Comment by NaoUnderscore** [comment]
There's no point, and even if there were, it'd not justify this breaking change.

**Comment by steven4547466** [comment]
Make this into a new `DisplayName` that returns `DisplayNickname ?? Nickname`

**Comment by Marco15453** [comment]
I have to agree with @NaoUnderscore

**Comment by joker-119** [comment]
This would be considered a breaking changes, as stated, this would break every plugin that checks if the DisplayNickname is null/empty before doing an action on it. This can be important for a plethora of reasons, but EXILED itself does this.
Objects that are able to be null are able to be null for a reason, and that behavior shouldn't be changed without a valid reason.

**Pull request closed without merging**
