### PR TITLE
EnteringKillerCollision event

### PR DESCRIPTION
**Pull request by Ficus-x**

### CODE REVIEW

**Comment by Monaldcry7788** [comment]
Idk if devs will accept this, it's better do a transpiler for the patch.

**Comment by Thundermaker300** [comment]
> Idk if devs will accept this, it's better do a transpiler for the patch.

iirc they accept non-transpiler patches and convert them to transpilers later on. may be wrong though

**Review by louis1706 — APPROVED** [review]

**Review by IRacle1 — APPROVED** [review]

**Review by rus-skill-issue — APPROVED** [review]

**Comment by PintTheDragon** [comment]
What does this allow that the Killing event doesn't?

**Comment by Ficus-x** [comment]
Killing event does not fire if the player has God mode

**Comment by PintTheDragon** [comment]
> Killing event does not fire if the player has God mode

So the killing by collision event will fire when a player won't actually be killed by collision?

**Comment by Ficus-x** [comment]
I understood what you mean that is why i renamed this event

**Review by Jesus-QC — APPROVED** [review]

**Pull request merged**
