### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by louis1706**
Add the Event DroppingScp330
&
Add the PickingUpScp330

### CODE REVIEW

**Comment by louis1706** [comment]
[HarmonyPatch(typeof(Scp330Bag), nameof(Scp330Bag.TryAddSpecific))]
	public class CandyPickup
    {
		public static bool Prefix(Scp330Bag __instance,ref bool __result,CandyKindID kind)
        {
			try
			{
				string Log = string.Empty;
				if (__instance.Candies.Count >= 6)
				{
					__result = false;
					return false;
				}
				__instance.Candies.Add(kind);
				Player player = Player.Get(__instance.Owner);
				__result = true;
				return false;
			}
			catch
            {
				Log.Error("Error in CandyPickup Prefix");
				return true;
			}
		}
	}
	[HarmonyPatch(typeof(Scp330Bag), nameof(Scp330Bag.TryRemove))]
	public class CandyDrop
    {
		public static bool Prefix(Scp330Bag __instance, ref CandyKindID __result,int index)
		{
			try
			{
				string Log = string.Empty;
				if (index < 0 || index > __instance.Candies.Count)
				{
					__result = CandyKindID.None;
					return false;
				}
				CandyKindID result = __instance.Candies[index];
				__instance.Candies.RemoveAt(index);
				__instance.ServerRefreshBag();
				Player player = Player.Get(__instance.Owner);
				__result = result;
				return false;
			}
			catch
			{
				Log.Error("Error in CandyPickup Prefix");
				return true;
			}
		}
	}
	
	The event is can be trigger by this method

**Comment by NaoUnderscore** [comment]
What

**Comment by SmusiJarviss** [comment]
tf is this thing lmao?

**Comment by joker-119** [comment]
Why are you trying to merge dev into master? Are you high?

**Comment by moddedmcplayer** [comment]
Bro ate too much baguette

**Pull request closed without merging**
