### PR TITLE
Exiled.Loader 6.9 & No more alias

### PR DESCRIPTION
**Pull request by louis1706**

### CODE REVIEW

**Comment by VALERA771** [comment]
Exiled 6.9 has a chance to exist?

**Comment by louis1706** [comment]
Technically 7.6.9 could exist

**Comment by VALERA771** [comment]
Huh. Really

**Comment by joker-119** [comment]
Why are we disabling aliases?

**Comment by louis1706** [comment]
> Why are we disabling aliases?

Because it's just horrible
 List<object>
 - &0e1
 - 0e1

**Comment by joker-119** [comment]
The change to the serializer also needs to be duplicated here: https://github.com/Exiled-Team/EXILED/blob/dev/Exiled.CustomRoles/CustomRoles.cs#L35

**Review by joker-119 — APPROVED** [review]

**Review by Misaka-ZeroTwo — APPROVED** [review]

**Pull request merged**
