### PR TITLE
Fix Player.Get(ServerHostPlayer)

### PR DESCRIPTION
**Pull request by louis1706**
Now Server.Host can trigger event and will not be null when attacking for example
(SpawnActive Grenade with Server.Host for example)

### CODE REVIEW

**Review by Michal78900 — APPROVED** [review]

**Comment by joker-119** [comment]
This in itself is not technically a *breaking* change, however it will change expected behavior for plugins. Delaying merge for 7.1

**Comment by louis1706** [comment]
> Now Server.Host can trigger event and will not be null when attacking for example (SpawnActive Grenade with Server.Host for example)

yeah that why i have make little precision in the description

**Comment by louis1706** [comment]
Step to reproduce 
- use SR
- Forceclass yourself to any role but don't start the round
- Disconect
- Get Spammed of LocalAdmingLogs error

**Comment by louis1706** [comment]
Do not merge actually causing bug

**Comment by louis1706** [comment]
it's seems than the bug is gone with one of the NPC fix but i am actually not sure if there more bug with it

**Comment by louis1706** [comment]
I have tested it today on my server it's seems fine now

**Pull request merged**
