### PR TITLE
Adding GetEffectType to extensions

### PR DESCRIPTION
**Pull request by Misaka-ZeroTwo**

### CODE REVIEW

**Comment by xNexus-ACS** [comment]
you forgot to add the AntiSCP207 and the Scanned status effects to the extensions

**Comment by Misaka-ZeroTwo** [comment]
> you forgot to add the AntiSCP207 and the Scanned status effects to the extensions

kind of intentional, because they are not in EffectType

**Comment by joker-119** [comment]
> > you forgot to add the AntiSCP207 and the Scanned status effects to the extensions
> 
> kind of intentional, because they are not in EffectType yet.

So add them.

**Comment by Misaka-ZeroTwo** [comment]
> > > you forgot to add the AntiSCP207 and the Scanned status effects to the extensions
> > 
> > 
> > kind of intentional, because they are not in EffectType yet.
> 
> So add them.

~~Lazy~~ lemme check how many effects are added.

**Review by Thundermaker300 — APPROVED** [review]

**Review by louis1706 — APPROVED** [review]

**Pull request merged**
