### PR TITLE
Adding AccessGranted parameter to Interacting door event

### PR DESCRIPTION
**Pull request by Misaka-ZeroTwo**
Adding the possibility to show access denied to Interacting door event

### CODE REVIEW

**Comment by Misaka-ZeroTwo** [comment]
Not tested

**Comment by louis1706** [comment]
> Not tested

Are you able to test it ?

**Comment by Misaka-ZeroTwo** [comment]
> > Not tested
> 
> Are you able to test it ?

No longer playing SL

**Comment by Misaka-ZeroTwo** [comment]
Breaking change

**Pull request closed without merging**
