### PR TITLE
Add DamageType extensions

### PR DESCRIPTION
**Pull request by Remuchi**

### CODE REVIEW

**Comment by Remuchi** [comment]
Idk if I should add scp-207 damagetype to IsScp or not

**Comment by Thundermaker300** [comment]
You should definitely add SCP-207 DamageType to IsScp, because it is damaged that is caused by an SCP (it'd be weird if it wasn't considered SCP damage). You could also add it to IsStatusEffect, but I'm not sure about that one

**Comment by Remuchi** [comment]
Maybe there should be IsPlayableScp and IsScp. IsPlayableScp only has playable SCPs like SCP106

**Comment by louis1706** [comment]
> Maybe there should be IsPlayableScp and IsScp. IsPlayableScp only has playable SCPs like SCP106

For IsScp you Can look with string if it the damagetype contain SCP idk if it more optimise

Like 
return damagetype.ToString().contains("Scp");

**Comment by Remuchi** [comment]
I don't think that returning a string value of enum type and when doing string search is more optimal than just bunch of byte(or whatever enum uses) comparisons

**Comment by louis1706** [comment]
> I don't think that returning a string value of enum type and when doing string search is more optimal than just bunch of byte(or whatever enum uses) comparisons 

Idk

**Comment by joker-119** [comment]
If you add SCP items to the IsScp one, I think there should be a bool that defaults true, and when it's false, the extension won't return true for the items, similar to our IsWeapon() extension for ItemTypes (ItemExtensions.IsWeapon) has one for excluding the MicroHid from the check.

**Pull request merged**
