### PR TITLE
[Breaking] Role properties

### PR DESCRIPTION
**Pull request by Thundermaker300**

### CODE REVIEW

**Comment by IRacle1** [comment]
these props also exists in `Player` class, so need to fix the duplicate

**Comment by Thundermaker300** [comment]
> these props also exists in `Player` class, so need to fix the duplicate

Oh right, I thought they were removed. Forgot to check lol

**Review by rus-skill-issue — APPROVED** [review]

**Comment by joker-119** [comment]
I'm like 99.999% certain they were purposefully left in the player class for ease of use.
``ev.Player.IsNtf`` is easier to type/remember than ``ev.Player.Role.IsNtf``

**Comment by Thundermaker300** [comment]
> I'm like 99.999% certain they were purposefully left in the player class for ease of use. `ev.Player.IsNtf` is easier to type/remember than `ev.Player.Role.IsNtf`

Ease of use yeah that makes sense, but it doesn't make sense logistically. yes, whether or not a player is an SCP is a player property (and hell, we can leave the properties on the player if we really want), they are also role information which should be available on the role class itself

**Review by NaoUnderscore — APPROVED** [review]

**Comment by joker-119** [comment]
> > I'm like 99.999% certain they were purposefully left in the player class for ease of use. `ev.Player.IsNtf` is easier to type/remember than `ev.Player.Role.IsNtf`
> 
> Ease of use yeah that makes sense, but it doesn't make sense logistically. yes, whether or not a player is an SCP is a player property (and hell, we can leave the properties on the player if we really want), they are also role information which should be available on the role class itself

Reasonable, and honestly I agree with you and these changes.
I just wanted to point out these were deliberately put here by someone at some point.

**Comment by joker-119** [comment]
Also fix brokey 2.0

**Comment by Thundermaker300** [comment]
idk how to fix the transpiler

**Review by Michal78900 — APPROVED** [review]

**Review by Michal78900 — CHANGES_REQUESTED** [review]
Fix build errors please

**Comment by Thundermaker300** [comment]
I do not know how to transpiler

**Comment by Thundermaker300** [comment]
Resigned

**Pull request closed without merging**
