### PR TITLE
FixNWSerialBeing 0

### PR DESCRIPTION
**Pull request by louis1706**

### CODE REVIEW

**Review by iopietro — APPROVED** [review]

**Comment by joker-119** [comment]
This can't be fixed in the getter like this.

If for ex, the base info serial is 0, this will generate a new serial for the return, but it does not update the base info to use the new serial, it remains 0 and thus will get another new serial the next time this getter is called, or when basegame assigns it one normally.

You need to also update the base info serial anytime you generate a new serial for the property return

**Comment by louis1706** [comment]
> This can't be fixed in the getter like this.
> 
> If for ex, the base info serial is 0, this will generate a new serial for the return, but it does not update the base info to use the new serial, it remains 0 and thus will get another new serial the next time this getter is called, or when basegame assigns it one normally.
> 
> You need to also update the base info serial anytime you generate a new serial for the property return

I use Serial setter so it's updated it ???

**Comment by IRacle1** [comment]
Serial equals to 0 is not a bug, its a valid state for non properly spawned items

**Comment by Thundermaker300** [comment]
Won't this make it so unspawned items will also have a serial?

**Comment by louis1706** [comment]
> Won't this make it so unspawned items will also have a serial?

that will never cause any issue

**Review by Thundermaker300 — APPROVED** [review]

**Pull request merged**
