### PR TITLE
dev into api-reworks

### PR DESCRIPTION
**Pull request by ALEXWARELLC**
We went through this.

Everything is conflict-fixed.

### CODE REVIEW

**Review by Misfiy — APPROVED** [review]

**Comment by Vladislav-CS** [comment]
I think we shouldn't merge dev from alex's repo, but from original

**Comment by ALEXWARELLC** [comment]
> I think we shouldn't merge dev from alex's repo, but from original

Could you elaborate a bit?

**Comment by VALERA771** [comment]
I agree with vlad. Even if we need to merge dev into apis brach we need to use our branches

**Comment by ALEXWARELLC** [comment]
> I agree with vlad. Even if we need to merge dev into apis brach we need to use our branches

@Misfiy

**Pull request closed without merging**
