### PR TITLE
Adding properties to classes

### PR DESCRIPTION
**Pull request by Thundermaker300**
mostly GameObject additions, some others  
properties that may be useful

### CODE REVIEW

**Review by NaoUnderscore — APPROVED** [review]

**Comment by joker-119** [comment]
Resolve file conflicts.

**Comment by Thundermaker300** [comment]
what the hell

**Comment by Thundermaker300** [comment]
Github told me that the branch wasn't being used anymore!!!!!!!!

**Comment by Thundermaker300** [comment]
i didnt know you could do that lmao

**Comment by joker-119** [comment]
Build errors go brr

**Pull request merged**
