### PR TITLE
Readding Exiled.Bootstrap

### PR DESCRIPTION
**Pull request by louis1706**

### CODE REVIEW

**Comment by iopietro** [comment]
Why?

**Comment by louis1706** [comment]
> Why?

Make possible to install Exiled with LocalAdmin plugin installer 

Remove Exiled dependency from NWdependency file

(Permitting a new way to update Exiled automatically)

**Comment by joker-119** [comment]
LA plugin installer can't install dependencies? :hmm:

**Comment by joker-119** [comment]
Why do we keep trying to reads this?this makes no sense.

**Pull request closed without merging**
