### PR TITLE
Update on Exiled docs

### PR DESCRIPTION
**Pull request by Misaka-ZeroTwo**

### CODE REVIEW

**Comment by Misaka-ZeroTwo** [comment]
@Ficus-x @MarcosVLl2 @Mikihero Localized readmes also need to update it.

**Comment by MarcosVLl2** [comment]
@Misaka-ZeroTwo Will do ASAP

**Comment by Mikihero** [comment]
It's a good time to fix a few other things in the pl one then, I'll work on it today

**Comment by Misaka-ZeroTwo** [comment]
I also just realized there are other parts of the readme requires changes. So no worries, let's fix the main readme first before working on localized version.

**Comment by Mikihero** [comment]
Lmk when main readme is up to date

**Review by iopietro — DISMISSED** [review]

**Comment by Misaka-ZeroTwo** [comment]
@Thundermaker300 pls review

**Review by Thundermaker300 — APPROVED** [review]
LGTM

**Comment by MarcosVLl2** [comment]
Done in #1535

**Review by iopietro — APPROVED** [review]

**Comment by Misaka-ZeroTwo** [comment]
@Mikihero Main is good now

**Comment by Mikihero** [comment]
I'll work on it when I get time

**Comment by Misaka-ZeroTwo** [comment]
No problem, take your time.

**Comment by Misaka-ZeroTwo** [comment]
Bruh, I can only request review from one person now.

**Comment by Mikihero** [comment]
Forgot to mention but mine's done in #1536

**Review by louis1706 — APPROVED** [review]

**Review by Thundermaker300 — APPROVED** [review]

**Pull request merged**
