### PR TITLE
Recoded Player.PreAuthenticating wia Patch

### PR DESCRIPTION
**Pull request by Marikider**
Recoded PreAuthenticating event wia patch, so IsAllowed will work.

### CODE REVIEW

**Review by xNexusACS — CHANGES_REQUESTED** [review]

**Review by xNexusACS — APPROVED** [review]

**Review by xNexusACS — CHANGES_REQUESTED** [review]
Fix build issues

**Review by xNexusACS — DISMISSED** [review]

**Review by xNexusACS — APPROVED** [review]

**Comment by xNexusACS** [comment]
Just some questions I have before merging this, what happens if `IsAllowed` is set to false? The player auth is rejected and go back to the main menu or the player is stuck in a loop in the loading screen?

Is this also fully tested? All properties returning the correct value, also making sure that this doesn't cause any issue with whitelists and server max slots.

**Comment by Marikider** [comment]
When IsAllowed is set to false, player goes back to lobby with Server Not Responding Message.  All Values in event args are same with original event are correct. Just tested it on reserved slots and whitelists, it is working and not cousing any troubles with it.

**Comment by xNexusACS** [comment]
> When IsAllowed is set to false, player goes back to lobby with Server Not Responding Message. All Values in event args are same with original event. Just tested it on reserved slots and whitelists, it is working and not cousing any troubles with it.

nice

**Pull request merged**
