### PR TITLE
Chinese README

### PR DESCRIPTION
**Pull request by zhaguanyang**

### CODE REVIEW

**Comment by zhaguanyang** [comment]
wrong base branch lol

**Comment by IRacle1** [comment]
`edit` -> `base branch` next time

**Comment by zhaguanyang** [comment]
> `edit` -> `base branch` next time

No, my master branch doesn't have the commits on it

**Comment by IRacle1** [comment]
> > `edit` -> `base branch` next time
> 
> No, my master branch doesn't have the commits on it

Oh, okay

**Pull request closed without merging**
