### PR TITLE
CustomRole::RegisterRoles(bool, object?, bool, Assembly?) fix

### PR DESCRIPTION
**Pull request by VALERA771**
inhernitAttributes now have a reason to exist

### CODE REVIEW

**Comment by joker-119** [comment]
The completely breaks using the attribute at all if you set inheritAttributes to false.

**Comment by VALERA771** [comment]
For me easier to override property instead of using attribute
So I thought that inheritAttributes parameter indicates should class has a CustomRole attribute

**Comment by joker-119** [comment]
Yea that's not at all what it's for. It's for use in the reflection, to determine if the attribute should be inherited if you are making an interface class between the api and your custom roles.

**Comment by VALERA771** [comment]
Huh. Ty

**Comment by Misaka-ZeroTwo** [comment]
build error

**Comment by VALERA771** [comment]
I think this PR should have enchantment label

**Comment by NaoUnderscore** [comment]
I don't really get the point of this PR

**Comment by VALERA771** [comment]
1. Allowing to register CustomRoles which define Type without attribute
2. Breaking changes. In CustomItems we have only 2 register methods and I don't see any reasons why we have here so much

**Comment by VALERA771** [comment]
Closing cuz CR API will be reworked

**Pull request closed without merging**
