### PR TITLE
Add string parameters overload to Log methods

### PR DESCRIPTION
**Pull request by Ceglaa**
I made this because it will optimise code a little bit, while you don't really need to .ToString() every time.

### CODE REVIEW

**Comment by NaoUnderscore** [comment]
May I ask what's going on here?

**Comment by Ceglaa** [comment]
i made it to avoid a value to get boxed and avoid to allocate more memory on the heap

**Comment by joker-119** [comment]
Build errors go brr

**Comment by Thundermaker300** [comment]
Merge upstream/dev into your branch to fix the build errors.

**Comment by Jesus-QC** [comment]
Fetch dev to fix build errors

**Pull request merged**
