### PR TITLE
Dummy API

### PR DESCRIPTION
**Pull request by gamehunt**
Converted Michal's prefixes to transpilers as he asked

### CODE REVIEW

**Comment by gamehunt** [comment]
Whoops, found tinybrain mistake, gona fix it rn

**Comment by joker-119** [comment]
This only fixes two of the potential issues with dummies. There are many, many more that would need to also get fixed to make them viable to be implemented within EXILED itself. We would also need to add an API to create dummies. Unless EXILED itself is going to create them via an API, I do not see why we should add patches to EXILED itself related to dummies.


Also re-merge dev branch into this PR plz.

**Comment by gamehunt** [comment]
Kk, should I convert this to draft for dummies api then? Also you can use those patches in the AT as a temporary fix anyway

**Comment by joker-119** [comment]
Probably yes

**Comment by gamehunt** [comment]
Closing this in favor of #843

**Pull request closed without merging**
