### PR TITLE
Re-implement ChangingIntoGrenade event

### PR DESCRIPTION
**Pull request by joker-119**
This patch re-implements the Map.ChangingIntoGrenade event, which will fire when an explodable pickup (IE HE grenade or 018) is turned into an active grenade when hit with an explosion.

The patch has been tested to not cause patching errors, but I have not yet verified the event works as expected and that base-game behavior isn't borked.

### CODE REVIEW

**Comment by Michal78900** [comment]
The event isn't called at all and the base-ga,e behavior is borked (grenade pickups aren't turned into grenades at all)

**Comment by joker-119** [comment]
> The event isn't called at all and the base-ga,e behavior is borked (grenade pickups aren't turned into grenades at all)

Are there any errors in the localadmin log?

**Comment by Michal78900** [comment]
> > The event isn't called at all and the base-ga,e behavior is borked (grenade pickups aren't turned into grenades at all)
> 
> Are there any errors in the localadmin log?

Yes
```
[2021-11-02 17:46:49.981 +01:00] [STDOUT] NullReferenceException: Object reference not set to an instance of an object
[2021-11-02 17:46:49.981 +01:00] [STDOUT]   at Exiled.Events.EventArgs.ChangingIntoGrenadeEventArgs..ctor (InventorySystem.Items.Pickups.ItemPickupBase pickup) [0x00014] in <992557609f30484e9a568ab9ac7131e7>:0
[2021-11-02 17:46:49.981 +01:00] [STDOUT]   at (wrapper dynamic-method) InventorySystem.Items.ThrowableProjectiles.TimedGrenadePickup.InventorySystem.Items.ThrowableProjectiles.TimedGrenadePickup.Update_Patch0(InventorySystem.Items.ThrowableProjectiles.TimedGrenadePickup)
[2021-11-02 17:46:49.981 +01:00] [STDOUT] (Filename: <992557609f30484e9a568ab9ac7131e7> Line: 0)
```

**Comment by joker-119** [comment]
> > > The event isn't called at all and the base-ga,e behavior is borked (grenade pickups aren't turned into grenades at all)
> > 
> > 
> > Are there any errors in the localadmin log?
> 
> Yes
> 
> ```
> [2021-11-02 17:46:49.981 +01:00] [STDOUT] NullReferenceException: Object reference not set to an instance of an object
> [2021-11-02 17:46:49.981 +01:00] [STDOUT]   at Exiled.Events.EventArgs.ChangingIntoGrenadeEventArgs..ctor (InventorySystem.Items.Pickups.ItemPickupBase pickup) [0x00014] in <992557609f30484e9a568ab9ac7131e7>:0
> [2021-11-02 17:46:49.981 +01:00] [STDOUT]   at (wrapper dynamic-method) InventorySystem.Items.ThrowableProjectiles.TimedGrenadePickup.InventorySystem.Items.ThrowableProjectiles.TimedGrenadePickup.Update_Patch0(InventorySystem.Items.ThrowableProjectiles.TimedGrenadePickup)
> [2021-11-02 17:46:49.981 +01:00] [STDOUT] (Filename: <992557609f30484e9a568ab9ac7131e7> Line: 0)
> ```

This has been resolved.

**Review by BuildBoy12 — APPROVED** [review]

**Pull request merged**
