### PR TITLE
Player::RemovePickup method

### PR DESCRIPTION
**Pull request by xNexus-ACS**

### CODE REVIEW

**Comment by joker-119** [comment]
By definition, a player cannot have a pickup in their inventory.

Doesn't player.RemoveItem(ushort serial) already exist?

**Comment by xNexus-ACS** [comment]
> By definition, a player cannot have a pickup in their inventory.
> 
> Doesn't player.RemoveItem(ushort serial) already exist?

We don't have any overload for RemoveItem that have ushort serial
I created that method for the thing that we can't get Pickups and remove them with this method bcs this method only have the Item parameter and the overload Func<Item, ...>

**Comment by joker-119** [comment]
I'd much rather this just be an overload for RemoveItem that accepts a ushort for the serial.

Because like i said, by definition, you cannot have a pickup in your inventory, so if you have a pickup reference and someone picks it up, you're either doing something really janky to keep that pickup reference alive, or your pickup reference should be null, since there's no pickup on the server as it is now an item in their inventory.

**Comment by xNexus-ACS** [comment]
> I'd much rather this just be an overload for RemoveItem that accepts a ushort for the serial.
> 
> Because like i said, by definition, you cannot have a pickup in your inventory, so if you have a pickup reference and someone picks it up, you're either doing something really janky to keep that pickup reference alive, or your pickup reference should be null, since there's no pickup on the server as it is now an item in their inventory.

sure, okay :)

**Comment by xNexus-ACS** [comment]
im going to close this pr then

**Pull request closed without merging**
