### PR TITLE
Fix component not being reset

### PR DESCRIPTION
**Pull request by louis1706**
- Thanks ArseeniK to report it

### CODE REVIEW

**Comment by IRacle1** [comment]
I think this is unnecessary here, in my opinion the problem is in the conditional check for null, if you write it with a check gameObject to null, I think there will be no problem

**Comment by IRacle1** [comment]
Perhaps this will solve all the problems of the cache

**Comment by IRacle1** [comment]
`scp914Controller ? scp914Controller : scp914Controller = Object::FindObjectOfType`

**Comment by louis1706** [comment]
> `scp914Controller ? scp914Controller : scp914Controller = Object::FindObjectOfType`

Ir's the than `scp914Controller ??= Object::FindObjectOfType`

**Review by Jesus-QC — APPROVED** [review]

**Pull request merged**
