### PR TITLE
feat(loader): log `LoaderExceptions` on `ReflectionTypeLoadException`

### LINKED ISSUE #1235: Log `LoaderExceptions` on `ReflectionTypeLoadException` in `Exiled.Loader.Loader.CreatePlugin`
It is not possible to understand the cause of the load error when a `ReflectionTypeLoadException` is thrown:
```
Error while initializing plugin ExamplePlugin (at )! System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
  at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <9577ac7a62ef43179789031239ba8798>:0
  at Exiled.Loader.Loader.CreatePlugin (System.Reflection.Assembly assembly) [0x00000] in <b2af369bf31047c496bb90b31b29c2d7>:0
```

According to the Microsoft documentation, `ReflectionTypeLoadException` has a `LoaderExceptions` property that allows you to find out the specific cause of the error:
https://docs.microsoft.com/en-us/dotnet/api/system.reflection.reflectiontypeloadexception.loaderexceptions?view=netframework-4.7.2

In this `catch` chain:
https://github.com/Exiled-Team/EXILED/blob/71ab70abaa12c9405bbf27daddf4546b34951a79/Exiled.Loader/Loader.cs#L287-L290
You just need to add:
```cs
catch(ReflectionTypeLoadException exception)
{
   Log.Error(exception.LoaderExceptions);
}
```
Unfortunately, I can't make this change myself at the moment.

### PR DESCRIPTION
**Pull request by Nekonyx**
resolves #1235

### CODE REVIEW

**Comment by joker-119** [comment]
Does this actually provide useful information, or just more undecipherable garbage?

**Comment by Nekonyx** [comment]
@joker-119 of course. Here is an example of when we have this patch:
```
[18:38:00] [ERROR] [Exiled.Loader] Error while initializing plugin ExamplePlugin (at )! System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
  at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <9577ac7a62ef43179789031239ba8798>:0
  at Exiled.Loader.Loader.CreatePlugin (System.Reflection.Assembly assembly) [0x00000] in <bca7e0acaae34b93b8a3962d05ce445c>:0
[18:38:00] [ERROR] [Exiled.Loader] System.IO.FileNotFoundException: Could not load file or assembly 'Exiled.CustomItems, Version=5.2.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'Exiled.CustomItems, Version=5.2.1.0, Culture=neutral, PublicKeyToken=null'
```
And here's an example of when we don't have that patch:
```
[18:38:00] [ERROR] [Exiled.Loader] Error while initializing plugin ExamplePlugin (at )! System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
  at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <9577ac7a62ef43179789031239ba8798>:0
  at Exiled.Loader.Loader.CreatePlugin (System.Reflection.Assembly assembly) [0x00000] in <bca7e0acaae34b93b8a3962d05ce445c>:0
```

**Comment by joker-119** [comment]
I just tested it myself aswell to make sure and see that, very nice I like it.

Not needed for this PR, but do you think it would be possible for us to make a parser for exceptions, something that can make these messages a little more understandable to end users, for example

```
[18:38:00] [ERROR] [Exiled.Loader] System.IO.FileNotFoundException: Could not load file or assembly 'Exiled.CustomItems, Version=5.2.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'Exiled.CustomItems, Version=5.2.1.0, Culture=neutral, PublicKeyToken=null'
```

Could instead be `[ERROR] [Exiled.Loader] Error while initializing plugin ExamplePlugin - Missing Dependency: "Exiled.CustomItems, Version=5.2.1.0"`
or something like that?

Anyways, this LGTM, good work <3

**Comment by Nekonyx** [comment]
> Could instead be `[ERROR] [Exiled.Loader] Error while initializing plugin ExamplePlugin - Missing Dependency: "Exiled.CustomItems, Version=5.2.1.0"` or something like that?

That would be very cool. Maybe I will someday, but at the moment and in the near future I definitely don't have free time for it.

> Anyways, this LGTM, good work <3

Thanks <3

**Review by joker-119 — APPROVED** [review]

**Comment by joker-119** [comment]
I just noticed, this PR should target dev, instead of master.

**Pull request merged**
