### PR TITLE
Camera.Type getter to use C# 9 switch statement

### PR DESCRIPTION
**Pull request by louis1706**

### CODE REVIEW

**Comment by IRacle1** [comment]
Kill Uwu and OwO

**Comment by louis1706** [comment]
> Kill Uwu and OwO
(￣y▽,￣)╭

**Comment by joker-119** [comment]
PR names in the future should always reflect what they are changing.

**Comment by louis1706** [comment]
> 

Okay sorry

**Comment by IRacle1** [comment]
> > Kill Uwu and OwO
> 
> (￣y▽,￣)╭

¯\_(ツ)_/¯

**Comment by joker-119** [comment]
> > PR names in the future should always reflect what they are changing.
> 
> Enforce git commit naming rule when kekw

Also this. No more obviously memey names for commits

**Pull request merged**
