### PR TITLE
Add spawn protection API to Respawn class

### PR DESCRIPTION
**Pull request by Thundermaker300**

### CODE REVIEW

**Review by louis1706 — COMMENTED** [review]
Can you add the SpawnProtected.Teams ?

**Review by louis1706 — APPROVED** [review]

**Review by Misaka-ZeroTwo — APPROVED** [review]

**Review by joker-119 — APPROVED** [review]
Personally I feel like these should be under the server API

But aside from that lgtm, if other devs think it belongs in respawn that's fine

**Comment by iopietro** [comment]
If we move them to the `Respawn` class, we should remove the `Spawn` prefix, so we don't have to type `Respawn.Spawn[...]` to call them.

**Comment by Thundermaker300** [comment]
I think it makes sense to put these in the Respawn class. Since, you know, they're all used solely for Respawning. With that said, I'll make pietro's change now.

**Review by iopietro — APPROVED** [review]

**Pull request merged**
