### PR TITLE
InteractedScp330 event

### PR DESCRIPTION
**Pull request by VALERA771**
Need someone else to test cuz I'm unable to test it. (this and InteractingScp330 event are not calling on my server, idk why, no patch errors)

### CODE REVIEW

**Comment by VALERA771** [comment]
Last time it wasn't working, so it was on draft

**Comment by ALEXWARELLC** [comment]
> Last time it wasn't working, so it was on draft

So am I able to perform tests on it?

**Comment by VALERA771** [comment]
You can try

**Comment by BoltonDev** [comment]
You should add `[EventPatch(typeof(Scp330), nameof(Scp330.InteractedScp330))]`

**Comment by Misfiy** [comment]
What happens in the case players hands is severed?
If it still calls, please add a variable for this
If it doesn't, maybe add it or make it another event

**Comment by VALERA771** [comment]
> What happens in the case players hands is severed? 

Just calls. Event does not depend on this

>If it still calls, please add a variable for this If it doesn't, maybe add it or make it another event

It can be easily done by checking if player has a severed hands effect. Do we really need this?

**Comment by Misfiy** [comment]
> It can be easily done by checking if player has a severed hands effect. Do we really need this?

Would be nice to have it be simple on whether players hands were severed
if you do not need to modify your transpiler then cool just add a bool in the event args for if player has severed effect

**Comment by VALERA771** [comment]
I'll close this for now cuz I saw that we are changing this method a lot so I idk how to correctly implement this event

**Pull request closed without merging**
