### PR TITLE
Make CustomRole appears above the name

### PR DESCRIPTION
**Pull request by louis1706**

### CODE REVIEW

**Review by Thundermaker300 — APPROVED** [review]

**Comment by louis1706** [comment]
Do not merge i will make a better change for this according to an actual suggestions on discord

**Comment by IRacle1** [comment]
It will break all plugins that changing players nicknames

**Comment by louis1706** [comment]
> It will break all plugins that changing players nicknames

only if they have CustomRole

**Comment by IRacle1** [comment]
> > It will break all plugins that changing players nicknames
> 
> only if they have CustomRole and if they change name after the Role Has been set

Yes, but it is the problem

**Comment by Thundermaker300** [comment]
We shouldn't be trying to judge what is more or less of a breaking change. If you make a change that changes a previously working feature to no longer work, it's a breaking change. That's all there is to it.

**Comment by IRacle1** [comment]
> We shouldn't be trying to judge what is more or less of a breaking change. If you make a change that changes a previously working feature to no longer work, it's a breaking change. Breaking changes are no longer allowed. That's all there is to it.

That pr is not like a breaking change, it breaks the displayed nickname system with custom roles at all, and we 2 ways:
- Write a complex patches/api/other things for supporting that
- Accept the fact that we wont be able to move CustomInfo😭

Personally I think this change is *too* insignificant to try implement it

**Pull request merged**
