### PR TITLE
Clone methods

### PR DESCRIPTION
**Pull request by Thundermaker300**

### CODE REVIEW

**Comment by Ficus-x** [comment]
Does cline methods make sense? 🤔

**Comment by Thundermaker300** [comment]
> Does cline methods make sense? 🤔

very simple API yes, but I'm sure someone somewhere out there could use it lol

**Comment by PintTheDragon** [comment]
> > Does cline methods make sense? thinking
> 
> very simple API yes, but I'm sure someone somewhere out there could use it lol

We shouldn't add things just to add things. I'm not completely sure what these would be used for.

**Comment by Thundermaker300** [comment]
> > > Does cline methods make sense? thinking
> > 
> > 
> > very simple API yes, but I'm sure someone somewhere out there could use it lol
> 
> We shouldn't add things just to add things. I'm not completely sure what these would be used for.

Fair point

**Pull request closed without merging**
