### PR TITLE
Improving Exiled.API.Features.Player.Get(string args)

### PR DESCRIPTION
**Pull request by Gnihtonen**
in Get(string args) useless additions to strings and GetDistance in this situation is too slow because we already know that secondString contains firstString => GetDistance = secondString.Length - firstString.Length (961 operations vs 1 operation).
Also we don't have to check firstString.Length < maxNameLength due to the same reason.

### CODE REVIEW

**Review by joker-119 — CHANGES_REQUESTED** [review]
Please re-base your patch on the `dev` branch, or switch the target branch and re-pull so we don't generate a ton of commit noise

**Comment by Michal78900** [comment]
Please fix build errors, remove unnecessary variables like `maxNameLength` and `lastnameDifference` (you don't use them at all)

**Comment by Michal78900** [comment]
Revert `Revert "Merge branch 'dev' into patch-1"` as it breaks stuff from other PRs right now

**Comment by Gnihtonen** [comment]
Yeah, sorry I'm using Git for the first time

**Comment by Michal78900** [comment]
`.github/workflows/docs.yml` is also needs to be reverted back to `dev` state

**Review by Michal78900 — APPROVED** [review]
Seems to be working
```cs
Log.Info(Player.Get(ev.Player.Nickname) != null);
Log.Info(Player.Get("Michal78900") != null);
Log.Info(Player.Get("Michal") != null);
Log.Info(Player.Get("78900") != null);
Log.Info(Player.Get("Amogus") != null);
Log.Info(Player.Get("asdasd") != null);
Log.Info(Player.Get(ev.Player.Nickname.Reverse().ToString()) != null);
```
image

**Review by PintTheDragon — APPROVED** [review]

**Review by Jesus-QC — CHANGES_REQUESTED** [review]
It looks great to me! Fix the issue.

**Review by Jesus-QC — APPROVED** [review]

**Review by joker-119 — APPROVED** [review]

**Pull request merged**
