### PR TITLE
Make all texts in config be quoted

### PR DESCRIPTION
**Pull request by VALERA771**
Time has come

### CODE REVIEW

**Comment by louis1706** [comment]
I would like to know if it's will break previous config ^^

**Comment by VALERA771** [comment]
Now I have problem that it's also makes properties be quoted. Not only values. So now I'm trying to fix this and then check that

**Comment by VALERA771** [comment]
Confirm that won't break configs

**Comment by VALERA771** [comment]
Alsp tested

**Review by louis1706 — CHANGES_REQUESTED** [review]
Fix Build Error

**Comment by louis1706** [comment]
> > Fix Build Error
> 
> What build error? All checks passed

yup sorry certainly miss refresh moment

**Review by louis1706 — APPROVED** [review]

**Pull request merged**
