### PR TITLE
**`New Documentation Website`**

### PR DESCRIPTION
**Pull request by Jesus-QC**
Preview:

https://jesus-qc.github.io/ExiledDocs/

### CODE REVIEW

**Comment by Thundermaker300** [comment]
hot

**Comment by zhaguanyang** [comment]
Looks cool

**Comment by Michal78900** [comment]
Please target `dev` branch

**Comment by Nekonyx** [comment]
Consider moving it to another repository

**Comment by NaoUnderscore** [comment]
Just make a new branch instead of merging it into dev/master. We're gonna keep and use it like the DocFx's one.

**Comment by Jesus-QC** [comment]
> Just make a new branch instead of merging it into dev/master. We're gonna keep and use it like the DocFx's one.

Wdym, gh-pages? thats automatically done by the bot

**Comment by Jesus-QC** [comment]
The actual doc-fx one is inside the main branch

**Comment by NaoUnderscore** [comment]
Ahh yes, my bad. I didn't mean that but whatever.

**Comment by Jesus-QC** [comment]
> Ahh yes, my bad. I didn't mean that but whatever.

So can you approv please

**Comment by NaoUnderscore** [comment]
> > Ahh yes, my bad. I didn't mean that but whatever.
> 
> So can you review and approve please

Seems ok

**Review by NaoUnderscore — APPROVED** [review]

**Pull request merged**
