### PR TITLE
GetMaxAmmo(Pickup) 

### PR DESCRIPTION
**Pull request by louis1706**

### CODE REVIEW

**Review by NaoUnderscore — CHANGES_REQUESTED** [review]
Firstly, documentation is bad. Ask @Thundermaker300 to add some valid docs.
Secondly, the code is bad and inefficient. Use a for loop and do what the base-game is doing to get all the attachments from `Firearm`/`FirearmPickup`s. Since we do not have an API for base-game pickups aside from the `ItemPickupBase`, we can't use the existing attachments API to interact/manipulate the attachments of `FirearmPickup`s as we're doing for `Item`s.

**Comment by Thundermaker300** [comment]
aaaaaaaaaaaaaaaaa

**Comment by louis1706** [comment]
Needs to be more efficient

**Comment by louis1706** [comment]
Nobody want to make it better xDDD

**Pull request closed without merging**
