### PR TITLE
939 lunge

### PR DESCRIPTION
**Pull request by VALERA771**
Tested by me and my friend

### CODE REVIEW

**Comment by xNexus-ACS** [comment]
why don't you fix the LungingEvent instead of creating a new one

**Comment by xNexus-ACS** [comment]
I put some suggestions if you want to make it much better

**Comment by xNexus-ACS** [comment]
also, I don't see why we need another event for it, why don't you fix the Lunging one instead of making a new one

**Comment by VALERA771** [comment]
> also, I don't see why we need another event for it, why don't you fix the Lunging one instead of making a new one, also your patch will need a rework

I couldn't fix it cuz patching method doesn't call at all. Can't find method that called before lunging

**Comment by louis1706** [comment]
Use Postfix to call the event and put every Lunging to Obsolete

**Comment by VALERA771** [comment]
> Use Postfix to call the event ~~and put every Lunging to Obsolete~~ 

I think I put everything to obsolete, will double clench

**Review by louis1706 — APPROVED** [review]

**Comment by Misaka-ZeroTwo** [comment]
Closes #1734

**Comment by VALERA771** [comment]
Gonna reopen it and make it new event (Misaka advice)

**Pull request closed without merging**
