### PR TITLE
Ability to scale custom items

### PR DESCRIPTION
**Pull request by RunicLib**
sorry for shitty commits, i'm fucked up with branches

### CODE REVIEW

**Comment by louis1706** [comment]
Make different branch When you doing a PR

**Comment by RunicLib** [comment]
> Make different branch When you doing a PR

ye ye, i forgor about this
i'm remembered when i'm going to open PR

**Comment by RunicLib** [comment]
> Okay strangely it's show your preview PR commits but it's already merged so ¯_(ツ)_/¯
=), it is main thing

**Review by Ficus-x — APPROVED** [review]

**Comment by RunicLib** [comment]
Need to add similar shit to grenades and weapons

**Review by rus-skill-issue — APPROVED** [review]

**Comment by RunicLib** [comment]
I think, that's all.
Other custom items based on parent class spawn method (`CustomItem::Spawn(Vector3, Item, Player)`)

**Comment by IRacle1** [comment]
You forgot CustomGrenade::Throw method(scale for grenades)

**Comment by RunicLib** [comment]
> You forgot CustomGrenade::Throw method(scale for grenades)

so, i need help with that
i tried to use few methods - unsuccessfully.

**Comment by RunicLib** [comment]
trouble only with projectile.
pickup resizes normally

**Comment by louis1706** [comment]
show the code

**Comment by IRacle1** [comment]
`thrownProjectile.gameObject.transform.localScale = Scale;`
before `NetworkServer.Spawn`, its works for me

**Comment by louis1706** [comment]
Wait no xD why i am assigned here ?

**Comment by RunicLib** [comment]
🫠

**Comment by RunicLib** [comment]
@Michal78900 how about to assign a labels to my shit? 👉👈🥺

**Review by Jesus-QC — APPROVED** [review]

**Pull request merged**
