### PR TITLE
Fixed description of Shot event

### PR DESCRIPTION
**Pull request by TeamEXAngus**
It's wrong and it was a pain in the ass for me

### CODE REVIEW

**Review by joker-119 — APPROVED** [review]
PR was made against wrong branch, only actual edit is Exiled.Events/Handlers/Player.cs L#179

Looks fine, I guess?

**Comment by iopietro** [comment]
This event isn't fired only when a player gets shot, but every time a bullet hits something.

**Comment by TeamEXAngus** [comment]
> This event isn't fired only when a player gets shot, but every time a bullet hits something.

When I was testing this event, it only triggered when players got shot, also this is what I got told in dev talk on the discord

**Comment by iopietro** [comment]
Mmh ok, then it's strange.

**Review by BuildBoy12 — APPROVED** [review]

**Pull request merged**
