### PR TITLE
Added Generator::Position

### PR DESCRIPTION
**Pull request by Monaldcry7788**

### CODE REVIEW

**Review by NaoUnderscore — CHANGES_REQUESTED** [review]
Add Transform and Rotation too.

**Comment by Ceglaa** [comment]
Maybe add NetworkServer.UnSpawn() and NetworkServer.Spawn() to the position/rotation set method? Same as in other object APIs

**Comment by NaoUnderscore** [comment]
> Maybe add NetworkServer.UnSpawn() and NetworkServer.Spawn() to the position/rotation set method? Same as in other object APIs

What

**Review by Michal78900 — CHANGES_REQUESTED** [review]
Setters won't work at all. I also think that UnSpawning and Spawning won't either, but I'm not sure.

**Pull request closed without merging**
