### PR TITLE
More SCP Events (106)

### PR DESCRIPTION
**Pull request by xNexus-ACS**

### CODE REVIEW

**Comment by xNexus-ACS** [comment]
I have tested all changed that I made, including all properties in the new event and all is working correctly

**Comment by xNexus-ACS** [comment]
image

**Comment by louis1706** [comment]
Same than 049 PR put TODO:// Rework Transpiler

**Comment by louis1706** [comment]
> image

it's better and less work to test it with the DevTools plugin from Sanye :3

**Comment by xNexus-ACS** [comment]
> Same than 049 PR put TODO:// Rework Transpiler

already did

**Comment by xNexus-ACS** [comment]
> > image
> 
> it's better and less work to test it with the DevTools plugin from Sanye :3

true, but I don't want my console spammed XD

**Comment by louis1706** [comment]
it's will be good to keep TeleportingEventArgs instead of UsingAtlas ? i don't disagree with it  

but it's will make an other break change for dev

**Comment by xNexus-ACS** [comment]
> it's will be good to keep TeleportingEventArgs instead of UsingAtlas ? i don't disagree with it
> 
> but it's will make an other break change for dev

The change to UsingAtlas is currently easier to understand since there is currently no teleport method as such like in 11.0, but now to teleport the player uses the Atlas

**Review by louis1706 — APPROVED** [review]

**Review by IRacle1 — APPROVED** [review]

**Pull request merged**
