### PR TITLE
Public secured PatchAll

### PR DESCRIPTION
**Pull request by louis1706**

### CODE REVIEW

**Comment by joker-119** [comment]
Ok but like... Why?

**Comment by louis1706** [comment]
> Ok but like... Why?

Why other plugin shouldn't have access to this ?

**Comment by louis1706** [comment]
> This should use GetCallingAssembly() not GetExecutingAssembly()

it's not the point of this PR if you want you can make an other PR

**Comment by o5zereth** [comment]
> > This should use GetCallingAssembly() not GetExecutingAssembly()
> 
> it's not the point of this PR if you want you can make an other PR

Uh, if you use GetExecutingAssembly your commit is completely useless, and will only patch the current assembly.

It quite literally requires the caller to have any point in being public.

My point is, your PR is wrong. You fix it, not me.

**Review by Thundermaker300 — APPROVED** [review]

**Review by NaoUnderscore — CHANGES_REQUESTED** [review]
Absolutely not.
`GlobalPatchProcessor` must not be marked as `static`, you must be able to inherit from it.

**Review by NaoUnderscore — APPROVED** [review]

**Pull request merged**
