### PR TITLE
Fix Scp018 pickup spawn.

### PR DESCRIPTION
**Pull request by Redforce04**

### CODE REVIEW

**Review by Misaka-ZeroTwo — APPROVED** [review]

**Comment by louis1706** [comment]
duplicate with this on #1545 (i will not close your PR in case if you will add more change)

**Review by Michal78900 — APPROVED** [review]

**Comment by Redforce04** [comment]
> duplicate with this on #1545 (i will not close your PR in case if you will add more change) 

I may add a projectile fix. Thanks for the heads up.

**Review by Thundermaker300 — APPROVED** [review]

**Comment by Thundermaker300** [comment]
Is this PR ready to be merged @Redforce04?

**Comment by Redforce04** [comment]
> Is this PR ready to be merged @Redforce04?

Go ahead, I'll fix the other issue in a new pr.

**Pull request merged**
