### PR TITLE
Change `Door.ChangeLock(lockType)` to `Door.Lock(lockType)`

### PR DESCRIPTION
**Pull request by RunicLib**
It maked for method overload ability and for saving main code styling.

### CODE REVIEW

**Review by Soft0101 — APPROVED** [review]
**Good PR from a good man.**

**Comment by IRacle1** [comment]
1. Why do you remove code in `ChangeLock`? That's breaking change
2. The method is not for locking doors, but for changing the lock state, your change is logically wrong

**Comment by IRacle1** [comment]
Also, solve merge conflicts

**Comment by RunicLib** [comment]
> 1. Why do you remove code in `ChangeLock`? That's breaking change
> 2. The method is not for locking doors, but for changing the lock state, your change is logically wrong

1. For overload method Lock(time, lockType)
2. Ok, idk about this logic.

There is a hole with naming methods. 
There is also a method to timed lock with name, which ghosting time-context. 
Mb let's implement a method that apply `DoorLockType.AdminCommand` to door lock?

**Comment by RunicLib** [comment]
wtf why i'm stucking with stashes

**Comment by RunicLib** [comment]
wtf is that
image

**Comment by RunicLib** [comment]
it isn't mine

**Comment by RunicLib** [comment]
hhm, as i told, that feature released in new beta
so strange, but ok
i'm sorry

**Pull request closed without merging**
