### PR TITLE
Blinking event ev.Player null fix

### PR DESCRIPTION
**Pull request by Misaka-ZeroTwo**

### CODE REVIEW

**Comment by Misaka-ZeroTwo** [comment]
Tested by issue reporter

**Comment by XiuerTalent** [comment]
Why was' flickerableLightController 'deleted

**Comment by Misaka-ZeroTwo** [comment]
> Why was' flickerableLightController 'deleted

That has nothing to do with this PR.

**Comment by Misaka-ZeroTwo** [comment]
And it's not deleted, but renamed to ``RoomLightController``

**Pull request merged**
