### PR TITLE
Fix error when LocalHub are null

### PR DESCRIPTION
**Pull request by louis1706**

### CODE REVIEW

**Comment by joker-119** [comment]
I LocalHub is null the entire game will break anyways, there's no point in routing around this error when the entire server will be fucked.

**Comment by louis1706** [comment]
I have tested it and i don't get any error with this

**Comment by louis1706** [comment]
I just receive this error
```System.InvalidOperationException: Nullable object must have a value.
  at System.Nullable`1[T].get_Value () [0x00008] in <9577ac7a62ef43179789031239ba8798>:0 
  at Exiled.API.Features.Round.get_IsStarted () [0x00024] in <98e24c451e14483982e7a4a9f707a436>:0 
  at UltimateAFK.PlayerEvents.OnDestroying (Exiled.Events.EventArgs.DestroyingEventArgs ev) [0x0007b] in <5fd5d4b4893d4ae4a0f81a396c6ba0a5>:0```

**Comment by louis1706** [comment]
Someone can reopen it i have done a terrible miss click

**Pull request merged**
