### PR TITLE
Add Cameras IEnumerable to Room

### PR DESCRIPTION
**Pull request by TheUltiOne**
Adds an IEnumerable which adds the room's cameras to it.

### CODE REVIEW

**Comment by joker-119** [comment]
All PRs should target the dev branch

**Comment by TheUltiOne** [comment]
Weird. I'm 100% sure I did do that.

**Comment by TheUltiOne** [comment]
the fuck
let me fix that

**Review by joker-119 — APPROVED** [review]
lgtm

**Review by PintTheDragon — APPROVED** [review]
Looks good

**Review by BuildBoy12 — APPROVED** [review]

**Pull request merged**
