### PR TITLE
Removing Obsolete

### PR DESCRIPTION
**Pull request by babyboucher**

### CODE REVIEW

**Review by Thundermaker300 — APPROVED** [review]

**Comment by joker-119** [comment]
The obsolete ctors are going to stay until 6.0 to avoid breaking **every** plugin that exists.

**Comment by babyboucher** [comment]
You said breaking changes tho

**Comment by joker-119** [comment]
I said breaking changes except removing the old item ctors

**Comment by joker-119** [comment]
Already done manually.

**Pull request closed without merging**
