### PR TITLE
Fix ChangingGroupEventArgs.NewGroup having no effect.

### PR DESCRIPTION
**Pull request by o5zereth**

### CODE REVIEW

**Comment by o5zereth** [comment]
@Misaka-ZeroTwo yes

**Review by Misaka-ZeroTwo — DISMISSED** [review]

**Review by VALERA771 — COMMENTED** [review]
I think group should be changing after checking IsAllowed

**Review by louis1706 — CHANGES_REQUESTED** [review]
Valera request is right it's should be done after the ev.IsAllowed

**Comment by o5zereth** [comment]
why does it matter? i would have to make a new local var which jusy makes the pr more complicated

**Comment by o5zereth** [comment]
> Valera request is right it's should be done after the ev.IsAllowed

why does it matter? i would have to make a new local var which just makes the pr more complicated.

its storing into the argument slot, which wont break anything. if it isnt allowed it will return anyways.

**Review by louis1706 — APPROVED** [review]

**Comment by Misaka-ZeroTwo** [comment]
Sorry, please target to dev branch cuz Halloween is ending.

**Comment by o5zereth** [comment]
Im tired of waiting, so im not wasting my time making a third pr. Do it yourself.

**Pull request closed without merging**
