### PR TITLE
Added more delay to GenerateCache

### LINKED ISSUE #1442: [BUG] Lockers property does not contain all lockers
**The list of lockers of Map does not contain all lockers**
The `Lockers` property of `Exiled.API.Features.Map` does not contain all lockers!
indeed if you call this method `UnityEngine.Object.FindObjectsOfType<Locker>()` when the round is in lunched, you get more locker than the property.

**To Reproduce**
1. create a plugin with a method attached to RoundStarted Event.
Get the Lockers by `UnityEngine.Object.FindObjectsOfType<Locker>();`
Get the Lockers by `Exiled.API.Features.Map.Lockers;`
- The attach method Server.RoundStarted
```cs
            var lockerFindObjects = UnityEngine.Object.FindObjectsOfType<Locker>();
            Log.Send("Lockers by UnityEngine.Object------------", Discord.LogLevel.Debug, ConsoleColor.Blue);
            foreach (var locker in lockerFindObjects)
            {
                Log.Debug(locker);
            }
            Log.Debug("Lockers by Exiled------------------------", Discord.LogLevel.Debug, ConsoleColor.Blue);
            foreach (var locker in Map.Lockers)
            {
                Log.Debug(locker);
            }
```
2. Start the serveur with the plugin...
3. Start round...
4. See the log

**Expected behavior**
Same value in `Lockers` and the value of `UnityEngine.Object.FindObjectsOfType<Locker>()`

**Server logs**
[Log.txt](https://github.com/Exiled-Team/EXILED/files/9914805/Log.txt)

**EXILED Version ("latest" is not a version):**
Exiled.Loader - Version 5.3.0

**Results of `show plugins` command in console:**
```
[2022-11-02 01:29:38.116 +01:00] Total number of plugins: 7
                                 Enabled plugins: 7
                                 Disabled plugins: 0

                                 Exiled.Events:
                                        - Author: Exiled Team
                                        - Version: 5.3.0.0
                                        - Required Exiled Version: 5.3.0.0
                                        - Prefix: exiled_events
                                        - Priority: Highest
                                 TestLocker:
                                        - Author: VT
                                        - Version: 1.0.0
                                        - Required Exiled Version: 5.3.0.0
                                        - Prefix: test_locker
                                        - Priority: Medium
                                 Exiled.Updater:
                                        - Author: Exiled.Updater
                                        - Version: 3.1.1.0
                                        - Required Exiled Version: 5.3.0.0
                                        - Prefix: exiled_updater
                                        - Priority: Medium
                                 Exiled.Permissions:
                                        - Author: Exiled Team
                                        - Version: 5.3.0.0
                                        - Required Exiled Version: 5.3.0.0
                                        - Prefix: exiled_permissions
                                        - Priority: Medium
                                 Exiled.CreditTags:
                                        - Author: Babyboucher20 & iRebbok & Exiled Team
                                        - Version: 5.3.0.0
                                        - Required Exiled Version: 5.3.0.0
                                        - Prefix: exiled_credits
                                        - Priority: Medium
                                 Exiled.CustomRoles:
                                        - Author: Exiled Team
                                        - Version: 5.3.0.0
                                        - Required Exiled Version: 5.3.0.0
                                        - Prefix: exiled_custom_roles
                                        - Priority: Medium
                                 Exiled.CustomItems:
                                        - Author: Exiled Team
                                        - Version: 5.3.0.0
                                        - Required Exiled Version: 5.3.0.0
                                        - Prefix: exiled_custom_items
                                        - Priority: Medium
```

### PR DESCRIPTION
**Pull request by Misaka-ZeroTwo**
fix #1442

### CODE REVIEW

**Comment by zhaguanyang** [comment]
Tested with 0.5 seconds, locker doesn't seem to generate at that time fully.

**Comment by zhaguanyang** [comment]
Test result with 1 second
```
[2022-11-03 02:13:04.087 +00:00] [INFO] [TestingPlugin] Lockers by UnityEngine.Object------------
[2022-11-03 02:13:04.099 +00:00] [DEBUG] [TestingPlugin] AdrenalineMedkitStructure(Clone) (MapGeneration.Distributors.Locker)
[2022-11-03 02:13:04.111 +00:00] [DEBUG] [TestingPlugin] AdrenalineMedkitStructure(Clone) (MapGeneration.Distributors.Locker)
[2022-11-03 02:13:04.123 +00:00] [DEBUG] [TestingPlugin] MiscLocker(Clone) (MapGeneration.Distributors.Locker)
[2022-11-03 02:13:04.136 +00:00] [DEBUG] [TestingPlugin] RegularMedkitStructure(Clone) (MapGeneration.Distributors.Locker)
[2022-11-03 02:13:04.148 +00:00] [DEBUG] [TestingPlugin] RegularMedkitStructure(Clone) (MapGeneration.Distributors.Locker)
[2022-11-03 02:13:04.159 +00:00] [DEBUG] [TestingPlugin] MiscLocker(Clone) (MapGeneration.Distributors.Locker)
[2022-11-03 02:13:04.171 +00:00] [DEBUG] [TestingPlugin] AdrenalineMedkitStructure(Clone) (MapGeneration.Distributors.Locker)
[2022-11-03 02:13:04.184 +00:00] [DEBUG] [TestingPlugin] Scp2176PedestalStructure Variant(Clone) (MapGeneration.Distributors.PedestalScpLocker)
[2022-11-03 02:13:04.196 +00:00] [DEBUG] [TestingPlugin] MiscLocker(Clone) (MapGeneration.Distributors.Locker)
[2022-11-03 02:13:04.209 +00:00] [DEBUG] [TestingPlugin] AdrenalineMedkitStructure(Clone) (MapGeneration.Distributors.Locker)
[2022-11-03 02:13:04.219 +00:00] [DEBUG] [TestingPlugin] Scp2176PedestalStructure Variant(Clone) (MapGeneration.Distributors.PedestalScpLocker)
[2022-11-03 02:13:04.231 +00:00] [DEBUG] [TestingPlugin] Scp1853PedestalStructure Variant(Clone) (MapGeneration.Distributors.PedestalScpLocker)
[2022-11-03 02:13:04.243 +00:00] [DEBUG] [TestingPlugin] Scp500PedestalStructure Variant(Clone) (MapGeneration.Distributors.PedestalScpLocker)
[2022-11-03 02:13:04.255 +00:00] [DEBUG] [TestingPlugin] AdrenalineMedkitStructure(Clone) (MapGeneration.Distributors.Locker)
[2022-11-03 02:13:04.268 +00:00] [DEBUG] [TestingPlugin] RegularMedkitStructure(Clone) (MapGeneration.Distributors.Locker)
[2022-11-03 02:13:04.280 +00:00] [DEBUG] [TestingPlugin] RegularMedkitStructure(Clone) (MapGeneration.Distributors.Locker)
[2022-11-03 02:13:04.291 +00:00] [DEBUG] [TestingPlugin] MiscLocker(Clone) (MapGeneration.Distributors.Locker)
[2022-11-03 02:13:04.303 +00:00] [DEBUG] [TestingPlugin] MiscLocker(Clone) (MapGeneration.Distributors.Locker)
[2022-11-03 02:13:04.315 +00:00] [DEBUG] [TestingPlugin] RifleRackStructure(Clone) (MapGeneration.Distributors.Locker)
[2022-11-03 02:13:04.328 +00:00] [DEBUG] [TestingPlugin] LargeGunLockerStructure(Clone) (MapGeneration.Distributors.Locker)
[2022-11-03 02:13:04.340 +00:00] [DEBUG] [TestingPlugin] Scp268PedestalStructure Variant(Clone) (MapGeneration.Distributors.PedestalScpLocker)
[2022-11-03 02:13:04.351 +00:00] [DEBUG] [TestingPlugin] Scp244PedestalStructure Variant(Clone) (MapGeneration.Distributors.PedestalScpLocker)
[2022-11-03 02:13:04.363 +00:00] [DEBUG] [TestingPlugin] Scp207PedestalStructure Variant(Clone) (MapGeneration.Distributors.PedestalScpLocker)
[2022-11-03 02:13:04.376 +00:00] [DEBUG] [TestingPlugin] Scp018PedestalStructure Variant(Clone) (MapGeneration.Distributors.PedestalScpLocker)
[2022-11-03 02:13:04.388 +00:00] [DEBUG] [TestingPlugin] RifleRackStructure (1) (MapGeneration.Distributors.Locker)
[2022-11-03 02:13:04.401 +00:00] [DEBUG] [TestingPlugin] RifleRackStructure (MapGeneration.Distributors.Locker)
[2022-11-03 02:13:04.411 +00:00] [INFO] [TestingPlugin] 26
[2022-11-03 02:13:04.424 +00:00] [INFO] [TestingPlugin] Lockers by Exiled------------------------
[2022-11-03 02:13:04.436 +00:00] [DEBUG] [TestingPlugin] AdrenalineMedkitStructure(Clone) (MapGeneration.Distributors.Locker)
[2022-11-03 02:13:04.448 +00:00] [DEBUG] [TestingPlugin] AdrenalineMedkitStructure(Clone) (MapGeneration.Distributors.Locker)
[2022-11-03 02:13:04.460 +00:00] [DEBUG] [TestingPlugin] MiscLocker(Clone) (MapGeneration.Distributors.Locker)
[2022-11-03 02:13:04.473 +00:00] [DEBUG] [TestingPlugin] RegularMedkitStructure(Clone) (MapGeneration.Distributors.Locker)
[2022-11-03 02:13:04.483 +00:00] [DEBUG] [TestingPlugin] RegularMedkitStructure(Clone) (MapGeneration.Distributors.Locker)
[2022-11-03 02:13:04.495 +00:00] [DEBUG] [TestingPlugin] MiscLocker(Clone) (MapGeneration.Distributors.Locker)
[2022-11-03 02:13:04.508 +00:00] [DEBUG] [TestingPlugin] AdrenalineMedkitStructure(Clone) (MapGeneration.Distributors.Locker)
[2022-11-03 02:13:04.520 +00:00] [DEBUG] [TestingPlugin] Scp2176PedestalStructure Variant(Clone) (MapGeneration.Distributors.PedestalScpLocker)
[2022-11-03 02:13:04.532 +00:00] [DEBUG] [TestingPlugin] MiscLocker(Clone) (MapGeneration.Distributors.Locker)
[2022-11-03 02:13:04.544 +00:00] [DEBUG] [TestingPlugin] AdrenalineMedkitStructure(Clone) (MapGeneration.Distributors.Locker)
[2022-11-03 02:13:04.555 +00:00] [DEBUG] [TestingPlugin] Scp2176PedestalStructure Variant(Clone) (MapGeneration.Distributors.PedestalScpLocker)
[2022-11-03 02:13:04.567 +00:00] [DEBUG] [TestingPlugin] Scp1853PedestalStructure Variant(Clone) (MapGeneration.Distributors.PedestalScpLocker)
[2022-11-03 02:13:04.579 +00:00] [DEBUG] [TestingPlugin] Scp500PedestalStructure Variant(Clone) (MapGeneration.Distributors.PedestalScpLocker)
[2022-11-03 02:13:04.591 +00:00] [DEBUG] [TestingPlugin] AdrenalineMedkitStructure(Clone) (MapGeneration.Distributors.Locker)
[2022-11-03 02:13:04.604 +00:00] [DEBUG] [TestingPlugin] RegularMedkitStructure(Clone) (MapGeneration.Distributors.Locker)
[2022-11-03 02:13:04.616 +00:00] [DEBUG] [TestingPlugin] RegularMedkitStructure(Clone) (MapGeneration.Distributors.Locker)
[2022-11-03 02:13:04.628 +00:00] [DEBUG] [TestingPlugin] MiscLocker(Clone) (MapGeneration.Distributors.Locker)
[2022-11-03 02:13:04.639 +00:00] [DEBUG] [TestingPlugin] MiscLocker(Clone) (MapGeneration.Distributors.Locker)
[2022-11-03 02:13:04.651 +00:00] [DEBUG] [TestingPlugin] RifleRackStructure(Clone) (MapGeneration.Distributors.Locker)
[2022-11-03 02:13:04.664 +00:00] [DEBUG] [TestingPlugin] LargeGunLockerStructure(Clone) (MapGeneration.Distributors.Locker)
[2022-11-03 02:13:04.677 +00:00] [DEBUG] [TestingPlugin] Scp268PedestalStructure Variant(Clone) (MapGeneration.Distributors.PedestalScpLocker)
[2022-11-03 02:13:04.687 +00:00] [DEBUG] [TestingPlugin] Scp244PedestalStructure Variant(Clone) (MapGeneration.Distributors.PedestalScpLocker)
[2022-11-03 02:13:04.700 +00:00] [DEBUG] [TestingPlugin] Scp207PedestalStructure Variant(Clone) (MapGeneration.Distributors.PedestalScpLocker)
[2022-11-03 02:13:04.712 +00:00] [DEBUG] [TestingPlugin] Scp018PedestalStructure Variant(Clone) (MapGeneration.Distributors.PedestalScpLocker)
[2022-11-03 02:13:04.723 +00:00] [DEBUG] [TestingPlugin] RifleRackStructure (1) (MapGeneration.Distributors.Locker)
[2022-11-03 02:13:04.735 +00:00] [DEBUG] [TestingPlugin] RifleRackStructure (MapGeneration.Distributors.Locker)
[2022-11-03 02:13:04.748 +00:00] [INFO] [TestingPlugin] 26
```

**Comment by zhaguanyang** [comment]
0.75 seconds also works, but I would prefer to make it 1 sec just to be safe.

**Comment by iopietro** [comment]
Fixed in Exiled-EA.

**Pull request closed without merging**
