### PR TITLE
Loader Rework

### PR DESCRIPTION
**Pull request by Jesus-QC**
### Added:

- [x] Individual Plugin Configs
- [x] Individual Plugin Translations
- [x] Commands to change between these distribution types
- [x] Loader Special Messages
- [x] Some Loader code enhancements and fixes
- [x] New extensions and methods

### New methods and extensions:
- Loader::GetPlugin
```cs
 var commonUtils = Loader.GetPlugin("CommonUtils");
```
- ConfigManager::LoadConfig
```cs
 var commonUtilsCfg = commonUtils.LoadConfig();
```
...
### Loader Special Messages (Based on month)
image

##### Default 
```yaml
Configs/
├─ XXXX-config.yml
├─ permissions.yml
├─ Loader-Configuration.yml
```
##### Separated
```yaml
Configs/
├─ Plugins/
│  ├─ common-utils/
│  │  ├─ 7777.yml
├─ permissions.yml
├─ Loader-Configuration.yml
```
##### Commands
```yaml
econfig
econfig merge
econfig split
```

### CODE REVIEW

**Comment by PintTheDragon** [comment]
I think it might be better if we put all of a plugin's configs in one folder. Ex group by plugin, config type instead of config type, plugin. That just makes it easier to modify an individual plugin.

**Comment by Jesus-QC** [comment]
@PintTheDragon do you mean like this?

```yaml
Configs/
├─ Plugins/
│  ├─ 7777/
│  │  ├─ common-utils.yml
├─ permissions.yml
├─ Loader-Configuration.yml
```

**Comment by PintTheDragon** [comment]
> @PintTheDragon do you mean like this?
> 
> ```yaml
> Configs/
> ├─ Plugins/
> │  ├─ 7777/
> │  │  ├─ common-utils.yml
> ├─ permissions.yml
> ├─ Loader-Configuration.yml
> ```

More like this:
```yaml
Configs/
├─ Plugins/
│  ├─ 7777/
│  │  ├─ CommonUtils
│  │  │  ├─ configs.yml
│  │  │  ├─ translations.yml
├─ permissions.yml
├─ Loader-Configuration.yml
```

The main benefit in that is that when someone wants to modify/add a specific plugin, they can do it all in one place.

**Comment by Jesus-QC** [comment]
Yeah, I could add that as a different config distribution since I created an enum for that future possibilities.

**Comment by Jesus-QC** [comment]
Im going to make some methods better for this cases

**Comment by Jesus-QC** [comment]
holy

**Review by joker-119 — APPROVED** [review]

**Review by Michal78900 — APPROVED** [review]

**Pull request merged**
