### PR TITLE
Fix ``TurnOffAllLights(float, ZoneType)``

### PR DESCRIPTION
**Pull request by louis1706**

### CODE REVIEW

**Comment by Jesus-QC** [comment]
Breaking Changes

**Comment by steven4547466** [comment]
Does this not conflict with the fixes to the flag in #1245? As the only reason this doesn't work right now is because the flag is messed up, right? So if this is merged, eventually when #1245 is merged, this will become no longer necessary and prevent turning lights off in multiple zones at the same time.

**Review by joker-119 — APPROVED** [review]

**Comment by louis1706** [comment]
> Not a breaking change.
> 
> This is ok as a temporary 'make it work' fix, but #1245 will need to make sure that these changes are reversed, or whatever is needed to make that PR's changes work properly.

It's because i have removed the flags property in ZoneType before

**Comment by Jesus-QC** [comment]
It was a breaking change, now it isnt

**Comment by Jesus-QC** [comment]
Should be reverted with #1245

**Pull request merged**
