### PR TITLE
Easy way to Goto AppData

### PR DESCRIPTION
**Pull request by Veslydev**
Uses %UserName% Instahead of (Your user) and make it easy Did in all langues

### CODE REVIEW

**Comment by 1EnesBaturKaza** [comment]
bad

**Comment by 1EnesBaturKaza** [comment]
good

**Comment by dogy1369** [comment]
usefull

**Comment by NotIntense** [comment]
You could also add (for Window users), press Win + R to bring up the Run box, then type %appdata% (not anything else) for it to instantly take you there.

**Comment by NaoUnderscore** [comment]
You may rename it to `User` instead of `UserName`, following MS docs.

**Comment by Veslydev** [comment]
> You may rename it to `User` instead of `UserName`, following MS docs.

User is not working i tried and it was not working, i checked the MS Docs And The best is put UserName on it

**Comment by XKaguya** [comment]
I think `%APPDATA%` is the easiest way to goto `AppData\Roaming`. Which type in explorer will directly into `C:\Users\Administrator\AppData\Roaming`

**Pull request merged**
