### PR TITLE
Add isSubtitles for Cassie (Message)

### PR DESCRIPTION
**Pull request by louis1706**

### CODE REVIEW

**Comment by joker-119** [comment]
Fix build errors.

Please ensure the solution actually builds before submitting PRs.

**Comment by louis1706** [comment]
> Fix build errors.
> 
> Please ensure the solution actually builds before submitting PRs.

Sorry i have don't get any error when i have generate it

**Comment by Thundermaker300** [comment]
The errors are from XML docs that you haven't fixed

**Comment by louis1706** [comment]
> The errors are from XML docs that you haven't fixed

Yes i fixed it latter i am not at home now

**Pull request merged**
