### PR TITLE
Scp049 use Player instead of uint id

### PR DESCRIPTION
**Pull request by louis1706**
i know it's breaking change but bruh

### CODE REVIEW

**Comment by VALERA771** [comment]
Can you change IEnumerable back to HashSet

**Comment by Misaka-ZeroTwo** [comment]
> Can you change IEnumerable back to HashSet

Why HashSet? It's a getter.

**Comment by VALERA771** [comment]
> > Can you change IEnumerable back to HashSet
> 
> 
> 
> Why HashSet? It's a getter.

Cuz there was a HashSet before. And wdym 'getter'?

**Comment by Misaka-ZeroTwo** [comment]
> Cuz there was a HashSet before. And wdym 'getter'?

Breaking change already, doesn't matter. And IEnumerable is the one that should be used cuz you are not editing that list.

**Review by Thundermaker300 — APPROVED** [review]

**Review by Misaka-ZeroTwo — APPROVED** [review]

**Pull request merged**
