### PR TITLE
Prevent certain events from firing if Player is not verified

### LINKED ISSUE #1802: [BUG] Events firing when player is not verified
**Describe the bug**
As described by the title.
**EXILED Version ("latest" is not a version):**
7.0.0-rc.2

### PR DESCRIPTION
**Pull request by Misaka-ZeroTwo**
Fix #1802 
Also added Player.IsNpc property so event would still fire for Npcs.

### CODE REVIEW

**Comment by joker-119** [comment]
why draft ;-;

**Comment by Misaka-ZeroTwo** [comment]
gonna add something funni real quick

**Comment by Misaka-ZeroTwo** [comment]
Do not merge due to #1806 broke it somehow. Can be merged once it's fixed.

**Comment by Misaka-ZeroTwo** [comment]
Issue resolved.

**Comment by Misaka-ZeroTwo** [comment]
draft again cuz just gonna reject the disconnect damage

**Pull request closed without merging**
