### PR TITLE
Better can sense tutorial

### PR DESCRIPTION
**Pull request by xNexus-ACS**

### CODE REVIEW

**Comment by xNexus-ACS** [comment]
not tested (do not merge)

**Comment by xNexus-ACS** [comment]
I will implement the yamato's suggest (Taking another player as target is the tutorial or turnedplayers condition is met) in another PR bcs it needs another patch and I want to implement that first

**Comment by xNexus-ACS** [comment]
Also tested and working

**Comment by louis1706** [comment]
I would say finish before merging

**Pull request merged**
