### PR TITLE
C# 9 features impelmentation

### PR DESCRIPTION
**Pull request by Lexa013**
- I switched the exiled C# version to C# 9
- I replaced the old switches

(More info in the commits messages)

### CODE REVIEW

**Comment by Jesus-QC** [comment]
image

**Comment by Lexa013** [comment]
Ur right, it's not "officially" supported, for instance c# 9 records don't compile but the rest for the most part is working fine. For now it's compiling fine so idk, i let the others contributors choose,

thx

**Comment by Lexa013** [comment]
Hey, any update on this PR, otherwise i'll close it.

Lexa,

**Comment by joker-119** [comment]
> Hey, any update on this PR ? Otherwise i'll close it.
> 
> Lexa,

None yet, but keep it open for the now. I will remind the other devs that this should be reviewed.

I assume you have been using this on your server without issue so far, yes?

**Comment by Lexa013** [comment]
> > Hey, any update on this PR ? Otherwise i'll close it.
> > Lexa,
> 
> None yet, but keep it open for the now. I will remind the other devs that this should be reviewed.
> 
> I assume you have been using this on your server without issue so far, yes?

Indeed without issues

**Comment by joker-119** [comment]
It has been decided not to pursue this as we would not be able to make use of all C# 9.0 functionality. Defining a lit of what 9.0 functionality is/isn't compatible with SL would be unrealistic, so we're sticking to the current language version.

**Pull request closed without merging**
