### PR TITLE
Add RoomType

### PR DESCRIPTION
**Pull request by sanyae2439**
Add RoomType for new rooms.

### CODE REVIEW

**Comment by sanyae2439** [comment]
HczStraight is still missing, so add it now.

**Comment by PintTheDragon** [comment]
Is it just mobile or is the formatting weird?

**Comment by babyboucher** [comment]
Looks fine to me

**Review by joker-119 — APPROVED** [review]

**Review by PintTheDragon — APPROVED** [review]
Yeah mobile being fucky.

**Review by BuildBoy12 — APPROVED** [review]

**Pull request merged**
