### PR TITLE
Small README update

### PR DESCRIPTION
**Pull request by VALERA771**
Fix for #2328

Should be checked if new limk is correct cuz i don't remember the previous page

### CODE REVIEW

**Comment by louis1706** [comment]
> Fix for #2328
> 
> Should be checked if new limk is correct cuz i don't remember the previous page

the link you did added is not updated (with actual exiled)

**Comment by VALERA771** [comment]
> > Fix for #2328
> 
> > 
> 
> > Should be checked if new limk is correct cuz i don't remember the previous page
> 
> 
> 
> the link you did added is not updated (with actual exiled) 

That's better than 404

**Comment by louis1706** [comment]
> > > Fix for #2328
> > 
> > 
> > > 
> > 
> > 
> > > Should be checked if new limk is correct cuz i don't remember the previous page
> > 
> > 
> > the link you did added is not updated (with actual exiled)
> 
> That's better than 404

it's still a not valid version of it

**Comment by VALERA771** [comment]
> > > > Fix for #2328
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > Should be checked if new limk is correct cuz i don't remember the previous page
> > > 
> > > 
> > > the link you did added is not updated (with actual exiled)
> > 
> > 
> > That's better than 404
> 
> it's still a not valid version of it

Any valid version or ways to update it? (I've never worked with EXILED's docs system)

**Comment by louis1706** [comment]
Nao will done a new website soon:tm:

**Pull request closed without merging**
