### PR TITLE
YamlDotNet using base game reference

### PR DESCRIPTION
**Pull request by IRacle1**
Using base game reference, we can forgot about YamlDotNet in our/nwapi deps folder, also for my plugins recompilation was not necessary for their work

### CODE REVIEW

**Review by iopietro — APPROVED** [review]

**Comment by IRacle1** [comment]
Looks like exiled references folder doesnt contains base game yamldotnet

**Comment by iopietro** [comment]
They use YamlDotNet 11.1.3, we use YamlDotNet 12.0.2.

**Comment by IRacle1** [comment]
Yes, but i dont specify dll version in csproj + i can build it without problems

**Comment by iopietro** [comment]
Ok, then it's fine.

**Review by iopietro — APPROVED** [review]

**Comment by louis1706** [comment]
(i have already said it on discord but just want to be sure this don't get merged)

This change will break some plugin who used nullable enum okay it's rare but since it's make a useless break change

**Comment by Thundermaker300** [comment]
Closing due to aforementioned issues by Yamato. Will reconsider if NW updates their version of yaml

**Pull request closed without merging**
