### PR TITLE
Ragdoll extensions fix

### PR DESCRIPTION
**Pull request by Jesus-QC**
@NaoUnderscore tinybrain

### CODE REVIEW

**Comment by NaoUnderscore** [comment]
No I'm not, it was supposed to be an extension for `Exiled.API.Features.Ragdoll`

**Comment by Jesus-QC** [comment]
Thats stupid

**Comment by Jesus-QC** [comment]
Read the history

**Comment by Jesus-QC** [comment]
I will just delete them and make a method to get the wrapper

**Comment by Jesus-QC** [comment]
#854 🤦🏻

**Pull request closed without merging**
